### ISSUE TITLE
Magic Cube Device Handler - lowercase bug

### ISSUE THREAD

**Issue by guffman** [veeceeoh/xiaomi-hubitat#17]
Line 196, the else if test for attired == "ff05" fails, as the actual device message contains "FF05". I changed the ff to uppercase and all is well with the rotation events.

**Comment by veeceeoh** [comment]
Thanks for the bug report.

This issue should now be resolved in the newly released v0.3b of the driver, available [here](https://raw.githubusercontent.com/veeceeoh/xiaomi-hubitat/master/devicedrivers/xiaomi-cube-controller-hubitat.src/xiaomi-cube-controller-hubitat.groovy).

Please see this [Hubitat Community post](https://community.hubitat.com/t/release-xiaomi-aqara-device-drivers/631/482) for more details on the update.
