### ISSUE TITLE
Xiaomi Aqara 2 Button Smart Switch - has no controls

### ISSUE THREAD

**Issue by jaffab** [veeceeoh/xiaomi-hubitat#25]
It would appear that the driver for the 2 button control switch has no commands.  Where the single button version has the expected on/off controls, for the 2 button version, it has only the reset of battery - nothing for the control of the actual 2 switches
![Aqara 2 button switch](https://user-images.githubusercontent.com/50545568/57581645-25483280-74b2-11e9-9659-4a5b8474bc72.png)

**Comment by veeceeoh** [comment]
I think you are confusing different Aqara products. 

My "Aqara Wireless Smart Light Switch" Hubitat driver is only to be used with the _battery-powered_ 2016 & 2018 revisions of models WXKG03LM (1 button) and WXKG02LM (2 buttons). These are just button devices, and cannot receive any commands.

It will not work with the _mains-powered_ Aqara Smart Light Switches, models QBKG03LM, QBKG04LM, QBKG11LM, and QBKG11LM. For those models you should use one of @guyeeba's Hubitat drivers, found [here](https://github.com/guyeeba/Hubitat/tree/master/Drivers).
